//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.ExampleWebApplication {
    
    
    public partial class DefaultHelpPage {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Erwine.Leonard.T.ExampleWebApplication.SiteMasterPage Master {
            get {
                return ((Erwine.Leonard.T.ExampleWebApplication.SiteMasterPage)(base.Master));
            }
        }
    }
}
