//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.ExampleWebApplication.BusinessObjects.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Folders = new HashSet<Folder>();
            this.Photos = new HashSet<Photo>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModfiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
    
        public virtual IdentityCache CreatorIdentityCache { get; set; }
        public virtual IdentityCache ModifierIdentityCache { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
