//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.ExampleWebApplication.BusinessObjects.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionCache
    {
        public System.Guid Id { get; set; }
        public System.Guid PhotoId { get; set; }
        public byte[] Data { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Format { get; set; }
        public byte[] MetaData { get; set; }
        public System.DateTime ConvertedOn { get; set; }
        public System.Guid ConvertedBy { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
    
        public virtual IdentityCache ConverterIdentityCache { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
