//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erwine.Leonard.T.ExampleWebApplication.BusinessObjects.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCache
    {
        public IdentityCache()
        {
            this.CreatedApplications = new HashSet<Application>();
            this.ModifiedApplications = new HashSet<Application>();
            this.ConversionCachePhotos = new HashSet<ConversionCache>();
            this.CreatedFolders = new HashSet<Folder>();
            this.ModifiedFolders = new HashSet<Folder>();
            this.CreatedPhotos = new HashSet<Photo>();
            this.ModifiedPhotos = new HashSet<Photo>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public string SID { get; set; }
        public string Domain { get; set; }
        public string Account { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime VerifiedOn { get; set; }
    
        public virtual ICollection<Application> CreatedApplications { get; set; }
        public virtual ICollection<Application> ModifiedApplications { get; set; }
        public virtual ICollection<ConversionCache> ConversionCachePhotos { get; set; }
        public virtual ICollection<Folder> CreatedFolders { get; set; }
        public virtual ICollection<Folder> ModifiedFolders { get; set; }
        public virtual ICollection<Photo> CreatedPhotos { get; set; }
        public virtual ICollection<Photo> ModifiedPhotos { get; set; }
    }
}
